name: Deployment

on:
    pull_request:
      branches:
        - "main"
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Get repo
      run: git clone https://github.com/FranciscoBodden/senderos.github.io.git
      name: Deployments

      on:
          pull_request:
            branches:
              - "main"
      jobs:
        test:
          runs-on: self-hosted
          steps:
          - uses: actions/checkout@v2
          - name: Get repo
            run: git clone https://github.com/FranciscoBodden/senderos.github.io.git