name: Deployment

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - "main"
      paths:
          - "**/*.css"
          - "**/*.html"
          - "**/*.js"
          - "*.css"
          - "*.html"
          - "*.js"
          - ".github/workflows/deploy.yml"
      types: [opened, synchronize, reopened, labeled]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Get repo
      run: git clone https://github.com/FranciscoBodden/senderos.github.io.git